#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm build
BUILD_STATUS=$?
if [ $BUILD_STATUS -ne 0 ]; then
  echo "Build failed. Commit aborted."
  exit 1
fi

pnpm test
TEST_STATUS=$?
if [ $TEST_STATUS -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

pnpm lint-staged
